folders:
  - folder_path: "odin"
    description: "everything around service odin"
jobs:
  - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/odin.git"
    jenkinsfile_path: "Jenkinsfile"