folders:
  - folder_path: "odin"
    description: "everything around service odin"
  - folder_path: "bifrost"
    description: "platform jobs to provision clusters and mapped services"
  - folder_path: "asgard-infra"
    description: "jobs to hold infrastructure pipelines"
jobs:
  - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/odin.git"
    jenkinsfile_path: "Jenkinsfile"
  - job_path: "bifrost/provision_cluster_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/bifrost-mapping.git"
    jenkinsfile_path: "Jenkinsfile"
  - job_path: "asgard-infra/cluster"
    jenkinsfile_git_repo: "git@github.com:ecsworkshop2018/asgard-infrastructure.git"
    jenkinsfile_path: "Jenkinsfile"
  - job_path: "asgard-infra/asg"
    jenkinsfile_git_repo: "git@github.com:ecsworkshop2018/asgard-infrastructure.git"
    jenkinsfile_path: "exercise3-solution/app-dns-and-alb/alb_dns_pipeline"