folders:
  - folder_path: "root_folder"
    description: "root_folder_description"
  - folder_path: "root_folder/sub_folder"
    description: "sub_folder_description"
jobs:
  - job_path: "root_folder/root_folder_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/seed_job.git"
    jenkinsfile_path: "sample_jenkins_file"