folders:
  - folder_path: "odin"
    description: "everything around service odin"
  - folder_path: "bifrost"
    description: "platform jobs to provision clusters and mapped services"
  - folder_path: "asgard-infra"
    description: "jobs to hold infrastructure pipelines"
  - folder_path: "thor"
    description: "everything around service thor"
jobs:
  - job_path: "odin/build_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/odin.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "bifrost/provision_cluster_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/bifrost-mapping.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "asgard-infra/cluster"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/asgard-infrastructure.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: false
  - job_path: "asgard-infra/asg"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/asgard-infrastructure.git"
    jenkinsfile_path: "exercise3-solution/app-dns-and-alb/alb_dns_pipeline"
    auto_trigger: false
  - job_path: "odin/deploy"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/odin-infrastructure.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "thor/build_job"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/thor.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "thor/deploy"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/thor-infrastructure.git"
    jenkinsfile_path: "Jenkinsfile"
    auto_trigger: true
  - job_path: "draining-lambda"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/draining-lambda.git"
    jenkinsfile_path: "dev/Jenkinsfile"
    auto_trigger: true
  - job_path: "scaling-lambda"
    jenkinsfile_git_repo: "https://github.com/ecsworkshop2018/scaling-lambda.git"
    jenkinsfile_path: "dev/Jenkinsfile"
    auto_trigger: true